#!/bin/bash

OUT_DIR=${1:-"/scratch4/$USER/bridge_sim"}
FLAG=$2
DAYS_TO_SIM=${DAYS_TO_SIM:-730}
JOBS_PER_NODE=${JOBS_PER_NODE:-12}
mkdir -p $OUT_DIR

# Support conda deactivate
MODULE_REF_FILE="/home/jsybran/module_groups/bridge_proj"
CONDA_PREP_FILE=~/anaconda3/etc/profile.d/conda.sh
source $CONDA_PREP_FILE
source $MODULE_REF_FILE

#Gets the directory containing this file
PROJ_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

SIM_BIN=$PROJ_DIR/bin/SimulateDay
DAILY_SIM_DESCRIPTIONS=$(mktemp)

for WORK_DIR in $(ls -d $OUT_DIR/*); do
  DAY_DIR=$WORK_DIR/daily_sim
  mkdir -p $DAY_DIR
  OUT_REF_FILE=$WORK_DIR/reference_data
  for DAY in $(seq $DAYS_TO_SIM); do
    if [[ ! -f "$DAY_DIR/$DAY.mat" ]]; then
      echo $OUT_REF_FILE $DAY $DAY_DIR/$DAY >> $DAILY_SIM_DESCRIPTIONS
    fi
  done
done

if [[ ! -z "$GO_BACKWARDS" ]]; then
  tac $DAILY_SIM_DESCRIPTIONS > tmp
  mv tmp $DAILY_SIM_DESCRIPTIONS
fi

if [[ $FLAG == '--dry-run' ]]; then
  cat $DAILY_SIM_DESCRIPTIONS
elif [[ -z $FLAG ]]; then
  echo "Simulating each day"
  parallel \
    --linebuffer \
    --sshloginfile "$PBS_NODEFILE" \
    --workdir $PROJ_DIR \
    -j $JOBS_PER_NODE \
    --colsep ' ' \
    """
    export MCR_CACHE_ROOT=\$(mktemp -d)
    REFERENCE_DATA={1}
    DAY={2}
    OUTPUT={3}
    source $CONDA_PREP_FILE
    source $MODULE_REF_FILE
    if [[ ! -f \$OUTPUT.mat ]]; then
      touch \$OUTPUT.mat
      $SIM_BIN \
        \$REFERENCE_DATA \
        \$DAY \
        \$OUTPUT
      echo Simulated \$OUTPUT
    else
      echo skipped \$OUTPUT
    fi
    rm -rf \$MCR_CACHE_ROOT
    """ < $DAILY_SIM_DESCRIPTIONS
else
  echo "Did not understand $FLAG"
  echo "Usage: ./run_sims.sh [--dry-run|--clean]"
  exit 1
fi
rm $DAILY_SIM_DESCRIPTIONS
