#!/bin/bash

MODEL_NAME=${1:-"conv"}
TARGET_DIR=${2:-"/scratch4/$USER/bridge_sim"}


if [[ ! -d $TARGET_DIR ]]; then
  echo "Must supply directory containing sims"
  echo "Usage: ./batch_compile_proto_stream path [--dry-run]"
  exit 1
fi

MODULE_REF_FILE="/home/jsybran/module_groups/bridge_proj"
CONDA_PREP_FILE=~/anaconda3/etc/profile.d/conda.sh
source $CONDA_PREP_FILE
source $MODULE_REF_FILE

PROJ_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
TRAIN_BIN=$PROJ_DIR/code/ml_model/train_model

  parallel \
    --linebuffer \
    --sshloginfile "$PBS_NODEFILE" \
    --workdir $PROJ_DIR \
    -j 1 \
    """
    TRAINING_DATA={}/data.pkl
    MODEL_OUT={}/"$MODEL_NAME"_model.h5
    NORMALIZER_OUT={}/"$MODEL_NAME"_normalizer.pkl
    DETAIL_CSV_OUT={}/"$MODEL_NAME"_training_details.csv
    if [[ -f \$TRAINING_DATA ]]; then
        source $CONDA_PREP_FILE
        source $MODULE_REF_FILE
        $TRAIN_BIN \$TRAINING_DATA \
          --model_out \$MODEL_OUT \
          --normalizer_out \$NORMALIZER_OUT \
          --training_detail_csv \$DETAIL_CSV_OUT
        echo {} Converged!
    else
      echo No training data found in {}
    fi
    """ ::: $(ls -d $TARGET_DIR/*)
