#!/bin/bash

MODEL_NAME=${1:-"conv"}
TARGET_DIR=${2:-"/scratch4/$USER/bridge_sim"}

if [[ ! -d $TARGET_DIR ]]; then
  echo "Must supply directory containing sims"
  echo "Usage: ./batch_compile_proto_stream path [--dry-run]"
  exit 1
fi

MODULE_REF_FILE="/home/jsybran/module_groups/bridge_proj"
CONDA_PREP_FILE=~/anaconda3/etc/profile.d/conda.sh
source $CONDA_PREP_FILE
source $MODULE_REF_FILE

PROJ_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
EVAL_BIN=$PROJ_DIR/code/ml_model/generate_confidence_plot

  parallel \
    --linebuffer \
    --sshloginfile "$PBS_NODEFILE" \
    --workdir $PROJ_DIR \
    -j 1 \
    --env EIGHT_CORE \
    """
    DATA_IN={}/data.pkl
    MODEL_IN={}/"$MODEL_NAME"_model.h5
    NORMALIZER_IN={}/"$MODEL_NAME"_normalizer.pkl
    EVAL_REPORT_OUT={}/"$MODEL_NAME"_conf_plot.png

    source $CONDA_PREP_FILE
    source $MODULE_REF_FILE
    $EVAL_BIN \
      --data \$DATA_IN \
      --model \$MODEL_IN \
      --normalizer \$NORMALIZER_IN \
      --output_file \$EVAL_REPORT_OUT
    echo DONE! {}
    """ ::: $(ls -d $TARGET_DIR/*)
